"""LLM-powered parser generator for ARGUS.

Automatically generates parsers for unknown file formats using Claude.
"""

import hashlib
import importlib.util
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Type

from argus.config import get_api_key
from argus.parsers.base import BaseParser, ParseResult, UnifiedEvent, EventSeverity


# Directory for custom generated parsers
CUSTOM_PARSERS_DIR = Path.home() / ".argus" / "custom_parsers"

# Template for generated parsers
PARSER_TEMPLATE = '''"""Auto-generated parser for {format_name}.

Generated by ARGUS on {generation_date}.
Source file sample: {source_file}
"""

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from argus.parsers.base import BaseParser, ParseResult, UnifiedEvent, EventSeverity


class {class_name}(BaseParser):
    """Parser for {format_description}."""

    name = "{parser_name}"
    description = "{format_description}"
    supported_extensions = {extensions}

    @classmethod
    def can_parse(cls, file_path: Path) -> bool:
        """Check if this parser can handle the file."""
{can_parse_body}

    def parse(self, file_path: Path) -> ParseResult:
        """Parse the file and extract events."""
        result = self._create_result(file_path)

{parse_body}

        return result

{helper_methods}
'''

# System prompt for parser generation
SYSTEM_PROMPT = """You are an expert log parser developer for ARGUS, an incident response tool.
Your task is to generate Python parser code that follows the ARGUS BaseParser pattern.

CRITICAL REQUIREMENTS:
1. The parser MUST inherit from BaseParser
2. The parser MUST implement can_parse(cls, file_path: Path) -> bool
3. The parser MUST implement parse(self, file_path: Path) -> ParseResult
4. Events MUST be UnifiedEvent instances with these key fields:
   - timestamp_utc: datetime (required)
   - source_file: str (required)
   - source_line: int (required)
   - event_type: str (required)
   - severity: EventSeverity (INFO, LOW, MEDIUM, HIGH, CRITICAL)
   - parser_name: str (use self.name)
   - Optional: source_ip, dest_ip, username, process_name, file_path, uri, etc.
5. Use result.add_event(event) to add events
6. Use result.add_warning() for non-fatal issues
7. Use result.add_error() for fatal parsing errors
8. Handle encoding with errors="ignore"
9. The can_parse method should check for unique indicators in the first few KB

Return ONLY valid Python code blocks for:
1. can_parse_body: The body of can_parse method (indented 8 spaces)
2. parse_body: The body of parse method (indented 8 spaces)
3. helper_methods: Any helper methods needed (indented 4 spaces, full method definitions)
4. extensions: List of file extensions like [".log", ".txt"]
5. format_description: Brief description of the format

Format your response as JSON:
{
    "can_parse_body": "...",
    "parse_body": "...",
    "helper_methods": "...",
    "extensions": [".log"],
    "format_description": "Description here"
}
"""


def sample_file(file_path: Path, max_lines: int = 50, max_bytes: int = 8192) -> str:
    """Sample a file for analysis.

    Args:
        file_path: Path to the file
        max_lines: Maximum number of lines to sample
        max_bytes: Maximum bytes to read

    Returns:
        String containing file sample
    """
    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read(max_bytes)

        lines = content.split("\n")[:max_lines]
        return "\n".join(lines)
    except Exception as e:
        return f"Error reading file: {e}"


def analyze_structure(content: str) -> dict:
    """Analyze file structure to help with parser generation.

    Args:
        content: File content sample

    Returns:
        Dict with structure analysis
    """
    analysis = {
        "line_count": len(content.split("\n")),
        "appears_json": False,
        "appears_csv": False,
        "appears_xml": False,
        "has_timestamps": False,
        "has_ip_addresses": False,
        "delimiter": None,
        "consistent_structure": False,
    }

    lines = [l.strip() for l in content.split("\n") if l.strip()]

    if not lines:
        return analysis

    # Check for JSON
    if lines[0].startswith("{") or lines[0].startswith("["):
        analysis["appears_json"] = True

    # Check for XML
    if lines[0].startswith("<?xml") or lines[0].startswith("<"):
        analysis["appears_xml"] = True

    # Check for CSV (consistent comma/tab counts)
    first_line = lines[0]
    comma_count = first_line.count(",")
    tab_count = first_line.count("\t")
    pipe_count = first_line.count("|")

    if comma_count > 2:
        consistent = all(l.count(",") == comma_count for l in lines[:10] if l)
        if consistent:
            analysis["appears_csv"] = True
            analysis["delimiter"] = ","
    elif tab_count > 1:
        consistent = all(l.count("\t") == tab_count for l in lines[:10] if l)
        if consistent:
            analysis["appears_csv"] = True
            analysis["delimiter"] = "\\t"
    elif pipe_count > 1:
        consistent = all(l.count("|") == pipe_count for l in lines[:10] if l)
        if consistent:
            analysis["appears_csv"] = True
            analysis["delimiter"] = "|"

    # Check for timestamps
    timestamp_patterns = [
        r"\d{4}-\d{2}-\d{2}",  # ISO date
        r"\d{2}/\d{2}/\d{4}",  # US date
        r"\d{2}:\d{2}:\d{2}",  # Time
        r"\w{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2}",  # Syslog
    ]
    for pattern in timestamp_patterns:
        if re.search(pattern, content):
            analysis["has_timestamps"] = True
            break

    # Check for IP addresses
    if re.search(r"\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}", content):
        analysis["has_ip_addresses"] = True

    return analysis


def generate_parser_code(
    file_path: Path,
    format_name: str,
    api_key: Optional[str] = None,
) -> Optional[str]:
    """Generate parser code using Claude.

    Args:
        file_path: Path to sample file
        format_name: Name for the format/parser
        api_key: Anthropic API key (uses config if not provided)

    Returns:
        Generated parser code as string, or None on failure
    """
    try:
        import anthropic
    except ImportError:
        raise ImportError("anthropic package required: pip install anthropic")

    # Get API key
    if not api_key:
        api_key = get_api_key("ANTHROPIC_API_KEY")

    if not api_key:
        raise ValueError("No Anthropic API key available")

    # Sample and analyze file
    sample = sample_file(file_path)
    analysis = analyze_structure(sample)

    # Build prompt
    user_prompt = f"""Generate a parser for this log format.

FILE: {file_path.name}
STRUCTURE ANALYSIS:
{json.dumps(analysis, indent=2)}

SAMPLE CONTENT (first ~50 lines):
```
{sample}
```

Generate parser code following the ARGUS BaseParser pattern.
The parser name should be: {format_name}
Class name should be: {format_name.title().replace('_', '').replace('-', '')}Parser

Focus on:
1. Reliable detection in can_parse (check for unique patterns)
2. Robust timestamp parsing
3. Extracting relevant security fields (IPs, users, actions, etc.)
4. Appropriate severity levels based on content
"""

    # Call Claude
    client = anthropic.Anthropic(api_key=api_key)

    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=4096,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_prompt}],
    )

    # Extract response
    response_text = response.content[0].text

    # Parse JSON from response
    json_match = re.search(r"\{[\s\S]*\}", response_text)
    if not json_match:
        raise ValueError("No JSON found in response")

    parsed = json.loads(json_match.group())

    # Build parser class name
    class_name = format_name.title().replace("_", "").replace("-", "") + "Parser"
    parser_name = format_name.lower().replace(" ", "_").replace("-", "_")

    # Generate full parser code
    code = PARSER_TEMPLATE.format(
        format_name=format_name,
        generation_date=datetime.now(timezone.utc).isoformat(),
        source_file=file_path.name,
        class_name=class_name,
        parser_name=parser_name,
        format_description=parsed.get("format_description", f"Auto-generated parser for {format_name}"),
        extensions=parsed.get("extensions", '[".log", ".txt"]'),
        can_parse_body=parsed.get("can_parse_body", "        return False"),
        parse_body=parsed.get("parse_body", "        pass"),
        helper_methods=parsed.get("helper_methods", ""),
    )

    return code


def validate_parser_code(code: str) -> tuple[bool, str]:
    """Validate that generated parser code is syntactically correct.

    Args:
        code: Python code string

    Returns:
        Tuple of (is_valid, error_message)
    """
    try:
        compile(code, "<generated>", "exec")
        return True, ""
    except SyntaxError as e:
        return False, f"Syntax error: {e}"


def save_custom_parser(
    code: str,
    parser_name: str,
    overwrite: bool = False,
) -> Path:
    """Save a custom parser to the custom parsers directory.

    Args:
        code: Parser code
        parser_name: Name for the parser file
        overwrite: Whether to overwrite existing

    Returns:
        Path to saved parser file
    """
    # Ensure directory exists
    CUSTOM_PARSERS_DIR.mkdir(parents=True, exist_ok=True)

    # Create __init__.py if needed
    init_file = CUSTOM_PARSERS_DIR / "__init__.py"
    if not init_file.exists():
        init_file.write_text('"""Custom ARGUS parsers."""\n')

    # Save parser
    filename = f"{parser_name.lower().replace(' ', '_').replace('-', '_')}.py"
    filepath = CUSTOM_PARSERS_DIR / filename

    if filepath.exists() and not overwrite:
        raise FileExistsError(f"Parser already exists: {filepath}")

    filepath.write_text(code)
    return filepath


def load_custom_parser(filepath: Path) -> Optional[Type[BaseParser]]:
    """Load a custom parser from a file.

    Args:
        filepath: Path to parser file

    Returns:
        Parser class, or None if loading fails
    """
    try:
        spec = importlib.util.spec_from_file_location(
            filepath.stem, filepath
        )
        if spec is None or spec.loader is None:
            return None

        module = importlib.util.module_from_spec(spec)
        sys.modules[filepath.stem] = module
        spec.loader.exec_module(module)

        # Find parser class
        for name in dir(module):
            obj = getattr(module, name)
            if (
                isinstance(obj, type)
                and issubclass(obj, BaseParser)
                and obj is not BaseParser
            ):
                return obj

        return None
    except Exception:
        return None


def load_all_custom_parsers() -> list[Type[BaseParser]]:
    """Load all custom parsers from the custom parsers directory.

    Returns:
        List of parser classes
    """
    parsers = []

    if not CUSTOM_PARSERS_DIR.exists():
        return parsers

    for filepath in CUSTOM_PARSERS_DIR.glob("*.py"):
        if filepath.name.startswith("_"):
            continue

        parser = load_custom_parser(filepath)
        if parser:
            parsers.append(parser)

    return parsers


def generate_and_save_parser(
    file_path: Path,
    format_name: Optional[str] = None,
    api_key: Optional[str] = None,
    validate: bool = True,
) -> tuple[Path, Type[BaseParser]]:
    """Generate, validate, and save a parser for an unknown file format.

    Args:
        file_path: Path to sample file
        format_name: Name for the format (derived from filename if not provided)
        api_key: Anthropic API key
        validate: Whether to validate the parser works

    Returns:
        Tuple of (parser_file_path, parser_class)
    """
    if not format_name:
        # Derive name from filename
        format_name = file_path.stem.split(".")[0].split("_")[0]

    # Generate code
    code = generate_parser_code(file_path, format_name, api_key)
    if not code:
        raise RuntimeError("Failed to generate parser code")

    # Validate syntax
    is_valid, error = validate_parser_code(code)
    if not is_valid:
        raise SyntaxError(f"Generated code has errors: {error}")

    # Save parser
    parser_path = save_custom_parser(code, format_name, overwrite=True)

    # Load and validate
    parser_class = load_custom_parser(parser_path)
    if not parser_class:
        raise RuntimeError("Failed to load generated parser")

    if validate:
        # Try to parse the sample file
        try:
            parser = parser_class()
            result = parser.parse(file_path)
            if result.errors:
                raise RuntimeError(f"Parser validation failed: {result.errors}")
        except Exception as e:
            raise RuntimeError(f"Parser validation failed: {e}")

    return parser_path, parser_class
