"""Phase 7: REPORT GENERATION.

Generates evidence figures, markdown report with analyst note placeholders,
and optional PDF conversion via WeasyPrint.
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional
import textwrap

import click

from argus.phases.phase0_init import write_completion_marker
from argus.phases.phase2_triage import check_phase_complete


REPORT_TEMPLATE = """# Incident Response Report

**Case ID:** {case_id}
**Generated:** {generated_at}
**Report Version:** 1.0
**Classification:** {classification}

---

## Executive Summary

{executive_summary}

[ANALYST NOTE: Review and customize executive summary for stakeholder communication]

---

## Timeline of Events

{timeline_section}

[ANALYST NOTE: Verify timeline accuracy and add context for key events]

---

## Attack Chain Analysis

{attack_chain_section}

---

## MITRE ATT&CK Coverage

{mitre_section}

---

## Indicators of Compromise

{ioc_section}

[ANALYST NOTE: Verify IOCs before sharing with external parties]

---

## Detection Recommendations

{detection_section}

---

## Evidence Summary

{evidence_section}

---

## Appendices

### A. Validated Claims

{claims_appendix}

### B. Sigma Rules

{sigma_appendix}

### C. Raw IOC List

{ioc_appendix}

---

## Report Metadata

- **Analysis Pipeline:** ARGUS v0.1.0
- **Phases Completed:** {phases_completed}
- **Total Events Analyzed:** {total_events}
- **Claims Generated:** {total_claims}
- **Claims Validated:** {validated_claims}
- **IOCs Extracted:** {total_iocs}
- **Sigma Rules Generated:** {sigma_rules}

[ANALYST NOTE: Add final review notes and sign-off]

---

*Report generated by ARGUS - Automated Response & Guided Unified Security*
"""


def load_case_metadata(case_path: Path) -> dict:
    """Load case metadata from argus.yaml."""
    import yaml

    yaml_path = case_path / "argus.yaml"
    if yaml_path.exists():
        with open(yaml_path) as f:
            return yaml.safe_load(f) or {}
    return {}


def load_analysis_summary(case_path: Path) -> dict:
    """Load analysis summary from Phase 3."""
    summary_file = case_path / "analysis" / "synthesis.json"
    if summary_file.exists():
        with open(summary_file) as f:
            return json.load(f)
    return {}


def load_validated_claims(case_path: Path) -> list[dict]:
    """Load validated claims from Phase 4."""
    claims_file = case_path / "validation" / "validated_claims.json"
    if claims_file.exists():
        with open(claims_file) as f:
            data = json.load(f)
            return data.get("claims", [])
    return []


def load_iocs(case_path: Path) -> dict:
    """Load IOCs from Phase 5."""
    ioc_file = case_path / "iocs" / "enriched_iocs.json"
    if ioc_file.exists():
        with open(ioc_file) as f:
            return json.load(f)
    return {"iocs": [], "total_iocs": 0}


def load_mitre_mapping(case_path: Path) -> list[dict]:
    """Load MITRE mapping from Phase 6."""
    mitre_file = case_path / "detection" / "mitre_mapping.json"
    if mitre_file.exists():
        with open(mitre_file) as f:
            data = json.load(f)
            return data.get("mappings", [])
    return []


def load_sigma_rules(case_path: Path) -> list[str]:
    """Load generated Sigma rules."""
    sigma_dir = case_path / "detection" / "sigma_rules"
    rules = []
    if sigma_dir.exists():
        for rule_file in sorted(sigma_dir.glob("*.yml")):
            with open(rule_file) as f:
                rules.append(f.read())
    return rules


def generate_executive_summary(synthesis: dict, claims: list, iocs: dict) -> str:
    """Generate executive summary from analysis data."""
    summary_parts = []

    # Get narrative if available
    narrative = synthesis.get("executive_narrative", "")
    if narrative:
        summary_parts.append(narrative)
    else:
        # Build basic summary
        summary_parts.append("This incident response analysis was conducted using automated forensic analysis techniques.")

    # Add key stats
    high_confidence = len([c for c in claims if c.get("confidence") == "HIGH"])
    high_risk_iocs = iocs.get("high_risk", 0)

    if high_confidence > 0:
        summary_parts.append(f"\n\n**Key Findings:** {high_confidence} high-confidence findings were identified during analysis.")

    if high_risk_iocs > 0:
        summary_parts.append(f"\n\n**Critical IOCs:** {high_risk_iocs} high-risk indicators of compromise were extracted and should be blocked immediately.")

    return "".join(summary_parts)


def generate_timeline_section(claims: list) -> str:
    """Generate timeline section from claims."""
    if not claims:
        return "*No timeline events available.*"

    # Sort claims by timestamp if available
    timed_claims = [c for c in claims if c.get("timestamp")]
    timed_claims.sort(key=lambda x: x.get("timestamp", ""))

    if not timed_claims:
        return "*Timeline data not available in claims.*"

    lines = ["| Timestamp | Event | Confidence |", "|-----------|-------|------------|"]

    for claim in timed_claims[:20]:  # Limit to 20 events
        ts = claim.get("timestamp", "N/A")
        summary = claim.get("summary", "")[:60]
        conf = claim.get("confidence", "MEDIUM")
        lines.append(f"| {ts} | {summary} | {conf} |")

    if len(timed_claims) > 20:
        lines.append(f"\n*... and {len(timed_claims) - 20} more events (see appendix)*")

    return "\n".join(lines)


def generate_attack_chain_section(synthesis: dict, mitre_mapping: list) -> str:
    """Generate attack chain analysis section."""
    sections = []

    # Attack chain from synthesis
    attack_chain = synthesis.get("attack_chain", [])
    if attack_chain:
        sections.append("### Attack Progression\n")
        for i, phase in enumerate(attack_chain, 1):
            phase_name = phase.get("phase", f"Phase {i}")
            description = phase.get("description", "")
            sections.append(f"**{i}. {phase_name}**\n{description}\n")

    # Tactic flow from MITRE
    if mitre_mapping:
        tactic_order = [
            "Initial Access", "Execution", "Persistence", "Privilege Escalation",
            "Defense Evasion", "Credential Access", "Discovery", "Lateral Movement",
            "Collection", "Command and Control", "Exfiltration", "Impact"
        ]

        observed_tactics = {}
        for mapping in mitre_mapping:
            tactic = mapping.get("tactic", "")
            if tactic:
                if tactic not in observed_tactics:
                    observed_tactics[tactic] = []
                observed_tactics[tactic].append(mapping)

        sections.append("\n### Observed Attack Phases\n")

        for tactic in tactic_order:
            if tactic in observed_tactics:
                techniques = observed_tactics[tactic]
                technique_list = ", ".join([f"{t['technique_id']}" for t in techniques])
                sections.append(f"- **{tactic}:** {technique_list}")

    if not sections:
        return "*Attack chain analysis not available.*"

    return "\n".join(sections)


def generate_mitre_section(mitre_mapping: list) -> str:
    """Generate MITRE ATT&CK section."""
    if not mitre_mapping:
        return "*No MITRE ATT&CK techniques identified.*"

    lines = [
        "The following MITRE ATT&CK techniques were observed:\n",
        "| Technique ID | Name | Tactic | Confidence |",
        "|--------------|------|--------|------------|"
    ]

    for mapping in mitre_mapping:
        lines.append(
            f"| {mapping.get('technique_id', 'N/A')} | "
            f"{mapping.get('technique_name', 'N/A')} | "
            f"{mapping.get('tactic', 'N/A')} | "
            f"{mapping.get('confidence', 'MEDIUM')} |"
        )

    return "\n".join(lines)


def generate_ioc_section(iocs: dict) -> str:
    """Generate IOC summary section."""
    ioc_list = iocs.get("iocs", [])
    if not ioc_list:
        return "*No IOCs extracted.*"

    # Group by type
    by_type = {}
    for ioc in ioc_list:
        ioc_type = ioc.get("type", "unknown")
        if ioc_type not in by_type:
            by_type[ioc_type] = []
        by_type[ioc_type].append(ioc)

    lines = ["### IOC Summary\n"]

    for ioc_type, items in by_type.items():
        high_risk = [i for i in items if i.get("risk_score", 0) >= 50]
        lines.append(f"- **{ioc_type.upper()}:** {len(items)} total, {len(high_risk)} high-risk")

    # Show top high-risk IOCs
    high_risk_all = [i for i in ioc_list if i.get("risk_score", 0) >= 50]
    if high_risk_all:
        lines.append("\n### High-Risk IOCs (Block Immediately)\n")
        lines.append("| Type | Value | Risk Score |")
        lines.append("|------|-------|------------|")

        for ioc in sorted(high_risk_all, key=lambda x: x.get("risk_score", 0), reverse=True)[:10]:
            lines.append(
                f"| {ioc.get('type', 'N/A')} | "
                f"`{ioc.get('value', 'N/A')[:50]}` | "
                f"{ioc.get('risk_score', 0)} |"
            )

    return "\n".join(lines)


def generate_detection_section(case_path: Path) -> str:
    """Generate detection recommendations section."""
    strategy_file = case_path / "detection" / "detection_strategy.md"

    if strategy_file.exists():
        with open(strategy_file) as f:
            content = f.read()
            # Extract key sections
            if "## Risk-Ranked Detection Priorities" in content:
                start = content.find("## Risk-Ranked Detection Priorities")
                end = content.find("## Coverage Gaps")
                if end > start:
                    return content[start:end].strip()

    return "*See detection_strategy.md for full recommendations.*"


def generate_evidence_section(case_path: Path) -> str:
    """Generate evidence summary section."""
    manifest_file = case_path / "evidence" / "manifest.json"

    if not manifest_file.exists():
        return "*No evidence manifest found.*"

    with open(manifest_file) as f:
        manifest = json.load(f)

    files = manifest.get("files", [])

    lines = [
        f"**Total Evidence Files:** {len(files)}\n",
        "| Filename | Type | Size | Hash |",
        "|----------|------|------|------|"
    ]

    for f in files[:15]:
        name = f.get("original_name", "N/A")[:30]
        file_type = f.get("detected_type", "unknown")
        size = f.get("size_bytes", 0)
        sha256 = f.get("sha256", "N/A")[:16] + "..."
        lines.append(f"| {name} | {file_type} | {size:,} bytes | {sha256} |")

    if len(files) > 15:
        lines.append(f"\n*... and {len(files) - 15} more files*")

    return "\n".join(lines)


def generate_claims_appendix(claims: list) -> str:
    """Generate claims appendix."""
    if not claims:
        return "*No validated claims.*"

    lines = []
    for i, claim in enumerate(claims, 1):
        claim_id = claim.get("claim_id", f"CLAIM-{i}")
        summary = claim.get("summary", "No summary")
        confidence = claim.get("confidence", "MEDIUM")
        validation = claim.get("validation_status", "UNVERIFIED")

        lines.append(f"**{claim_id}** [{confidence}] [{validation}]")
        lines.append(f"> {summary}\n")

    return "\n".join(lines)


def generate_sigma_appendix(rules: list) -> str:
    """Generate Sigma rules appendix."""
    if not rules:
        return "*No Sigma rules generated.*"

    lines = []
    for i, rule in enumerate(rules, 1):
        lines.append(f"#### Rule {i}\n")
        lines.append(f"```yaml\n{rule}\n```\n")

    return "\n".join(lines)


def generate_ioc_appendix(iocs: dict) -> str:
    """Generate raw IOC list appendix."""
    ioc_list = iocs.get("iocs", [])
    if not ioc_list:
        return "*No IOCs.*"

    # Group by type
    by_type = {}
    for ioc in ioc_list:
        ioc_type = ioc.get("type", "unknown")
        if ioc_type not in by_type:
            by_type[ioc_type] = []
        by_type[ioc_type].append(ioc.get("value", ""))

    lines = []
    for ioc_type, values in by_type.items():
        lines.append(f"**{ioc_type.upper()}:**")
        lines.append("```")
        for v in values:
            lines.append(v)
        lines.append("```\n")

    return "\n".join(lines)


def count_phases_completed(case_path: Path) -> int:
    """Count how many phases are complete."""
    completed = 0
    for phase in range(7):
        if check_phase_complete(case_path, phase):
            completed += 1
    return completed


def generate_markdown_report(case_path: Path) -> str:
    """Generate the full markdown report."""
    # Load all data
    metadata = load_case_metadata(case_path)
    synthesis = load_analysis_summary(case_path)
    claims = load_validated_claims(case_path)
    iocs = load_iocs(case_path)
    mitre_mapping = load_mitre_mapping(case_path)
    sigma_rules = load_sigma_rules(case_path)

    # Generate sections
    report = REPORT_TEMPLATE.format(
        case_id=metadata.get("case_id", case_path.name),
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        classification=metadata.get("classification", "INTERNAL"),
        executive_summary=generate_executive_summary(synthesis, claims, iocs),
        timeline_section=generate_timeline_section(claims),
        attack_chain_section=generate_attack_chain_section(synthesis, mitre_mapping),
        mitre_section=generate_mitre_section(mitre_mapping),
        ioc_section=generate_ioc_section(iocs),
        detection_section=generate_detection_section(case_path),
        evidence_section=generate_evidence_section(case_path),
        claims_appendix=generate_claims_appendix(claims),
        sigma_appendix=generate_sigma_appendix(sigma_rules),
        ioc_appendix=generate_ioc_appendix(iocs),
        phases_completed=count_phases_completed(case_path),
        total_events=synthesis.get("events_analyzed", 0),
        total_claims=len(claims),
        validated_claims=len([c for c in claims if c.get("validation_status") == "VERIFIED"]),
        total_iocs=iocs.get("total_iocs", 0),
        sigma_rules=len(sigma_rules),
    )

    return report


def convert_to_pdf(markdown_path: Path, pdf_path: Path) -> bool:
    """Convert markdown to PDF using WeasyPrint."""
    try:
        import markdown
        from weasyprint import HTML, CSS

        # Read markdown
        with open(markdown_path) as f:
            md_content = f.read()

        # Convert to HTML
        html_content = markdown.markdown(
            md_content,
            extensions=['tables', 'fenced_code', 'toc']
        )

        # Wrap in HTML template
        full_html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>ARGUS Incident Response Report</title>
        </head>
        <body>
            {html_content}
        </body>
        </html>
        """

        # CSS for PDF
        css = CSS(string="""
            body {
                font-family: Arial, sans-serif;
                font-size: 11pt;
                line-height: 1.4;
                margin: 2cm;
            }
            h1 { font-size: 24pt; color: #1a1a2e; border-bottom: 2px solid #1a1a2e; }
            h2 { font-size: 18pt; color: #16213e; margin-top: 1.5em; }
            h3 { font-size: 14pt; color: #0f3460; }
            table { border-collapse: collapse; width: 100%; margin: 1em 0; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #1a1a2e; color: white; }
            code { background-color: #f4f4f4; padding: 2px 6px; font-family: monospace; }
            pre { background-color: #f4f4f4; padding: 1em; overflow-x: auto; }
            blockquote { border-left: 4px solid #ccc; margin-left: 0; padding-left: 1em; }
            hr { border: none; border-top: 1px solid #ccc; margin: 2em 0; }
            @page { margin: 2cm; }
        """)

        # Generate PDF
        HTML(string=full_html).write_pdf(pdf_path, stylesheets=[css])
        return True

    except ImportError as e:
        click.echo(f"  PDF conversion requires: pip install weasyprint markdown")
        click.echo(f"  Missing: {e}")
        return False
    except Exception as e:
        click.echo(f"  PDF conversion failed: {e}")
        return False


def run_report_generation(case_path_str: str, pdf: bool = True) -> bool:
    """Run Phase 7: Report Generation.

    Args:
        case_path_str: Path to case directory
        pdf: Whether to generate PDF version

    Returns:
        True if successful
    """
    case_path = Path(case_path_str).resolve()

    # Verify case exists
    if not (case_path / "argus.yaml").exists():
        click.echo("Error: Not a valid ARGUS case directory", err=True)
        return False

    # Check if Phase 6 is complete
    if not check_phase_complete(case_path, 6):
        click.echo("Phase 6 not complete. Running detection engineering first...")
        from argus.phases.phase6_detection import run_detection_engineering
        if not run_detection_engineering(case_path_str):
            click.echo("Detection engineering failed. Cannot proceed.")
            return False

    report_dir = case_path / "report"
    report_dir.mkdir(exist_ok=True)

    click.echo(f"\nPhase 7: REPORT GENERATION")
    click.echo("=" * 40)

    # Generate markdown report
    click.echo("\nGenerating markdown report...")
    report_content = generate_markdown_report(case_path)

    md_path = report_dir / "incident_report.md"
    with open(md_path, "w") as f:
        f.write(report_content)

    click.echo(f"  Markdown report: {md_path.name}")

    # Generate PDF if requested
    pdf_generated = False
    if pdf:
        click.echo("\nConverting to PDF...")
        pdf_path = report_dir / "incident_report.pdf"
        pdf_generated = convert_to_pdf(md_path, pdf_path)
        if pdf_generated:
            click.echo(f"  PDF report: {pdf_path.name}")

    # Summary
    click.echo("\n" + "=" * 40)
    click.echo("Report Generation Summary")
    click.echo("=" * 40)
    click.echo(f"  Markdown:  {md_path.name}")
    if pdf_generated:
        click.echo(f"  PDF:       incident_report.pdf")
    else:
        click.echo("  PDF:       Not generated (install weasyprint)")

    # Write completion marker
    write_completion_marker(case_path, 7)

    click.echo(f"\nPhase 7 complete. Results in: {report_dir}")
    return True
